provider: opsgenie
major-version: 1
esc:
  enabled: true
env:
  OPSGENIE_API_KEY: ${{ secrets.OPSGENIE_API_KEY }}
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
plugins:
  - name: std
    version: "1.6.2"

  - name: terraform
    version: "1.0.16"
    kind: converter
