provider: opsgenie
major-version: 1
esc:
    enabled: true
env:
    OPSGENIE_API_KEY: ${{ secrets.OPSGENIE_API_KEY }}
makeTemplate: bridged
renovateCmd: make tfgen schema build_sdks
team: ecosystem
pulumiConvert: 1
registryDocs: true
