// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi-opsgenie/sdk/go/opsgenie/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "opsgenie:apiKey")
}
func GetApiRetryCount(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "opsgenie:apiRetryCount")
}
func GetApiRetryWaitMax(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "opsgenie:apiRetryWaitMax")
}
func GetApiRetryWaitMin(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "opsgenie:apiRetryWaitMin")
}
func GetApiUrl(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "opsgenie:apiUrl")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "OPSGENIE_API_URL"); d != nil {
		value = d.(string)
	}
	return value
}
