// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.opsgenie.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.opsgenie.outputs.IntegrationActionCreateFilter;
import com.pulumi.opsgenie.outputs.IntegrationActionCreateResponder;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class IntegrationActionCreate {
    private final @Nullable List<String> alertActions;
    /**
     * @return An identifier that is used for alert deduplication. Default: `{{alias}}`.
     * 
     */
    private final @Nullable String alias;
    private final @Nullable Boolean appendAttachments;
    /**
     * @return Custom alert priority. e.g. ``{{message.substring(0,2)}}``
     * 
     */
    private final @Nullable String customPriority;
    /**
     * @return Detailed description of the alert, anything that may not have fit in the `message` field.
     * 
     */
    private final @Nullable String description;
    /**
     * @return The entity the alert is related to.
     * 
     */
    private final @Nullable String entity;
    /**
     * @return Set of user defined properties specified as a map.
     * 
     */
    private final @Nullable Map<String,String> extraProperties;
    /**
     * @return Used to specify rules for matching alerts and the filter type. Please note that depending on the integration type the field names in the filter conditions are:
     * * For SNS integration: `actions`, `alias`, `entity`, `Message`, `recipients`, `responders`, `Subject`, `tags`, `teams`, `eventType`, `Timestamp`, `TopicArn`.
     * * For API integration: `message`, `alias`, `description`, `source`, `entity`, `tags`, `actions`, `details`, `extra-properties`, `recipients`, `teams`, `priority`, `eventType`.
     * * For Email integration: `from_address`, `from_name`, `conversationSubject`, `subject`
     * 
     */
    private final @Nullable List<IntegrationActionCreateFilter> filters;
    private final @Nullable Boolean ignoreAlertActionsFromPayload;
    private final @Nullable Boolean ignoreExtraPropertiesFromPayload;
    /**
     * @return If enabled, the integration will ignore responders sent in request payloads.
     * 
     */
    private final @Nullable Boolean ignoreRespondersFromPayload;
    private final @Nullable Boolean ignoreTagsFromPayload;
    /**
     * @return If enabled, the integration will ignore teams sent in request payloads.
     * 
     */
    private final @Nullable Boolean ignoreTeamsFromPayload;
    /**
     * @return Alert text limited to 130 characters.
     * 
     */
    private final @Nullable String message;
    /**
     * @return Name of the integration action.
     * 
     */
    private final String name;
    /**
     * @return Additional alert action note.
     * 
     */
    private final @Nullable String note;
    /**
     * @return Integer value that defines in which order the action will be performed. Default: `1`.
     * 
     */
    private final @Nullable Integer order;
    /**
     * @return Alert priority.
     * 
     */
    private final @Nullable String priority;
    /**
     * @return User, schedule, teams or escalation names to calculate which users will receive notifications of the alert.
     * 
     */
    private final @Nullable List<IntegrationActionCreateResponder> responders;
    /**
     * @return User defined field to specify source of action.
     * 
     */
    private final @Nullable String source;
    /**
     * @return Comma separated list of labels to be attached to the alert.
     * 
     */
    private final @Nullable List<String> tags;
    /**
     * @return The responder type - can be `escalation`, `team` or `user`.
     * 
     */
    private final @Nullable String type;
    /**
     * @return Owner of the execution for integration action.
     * 
     */
    private final @Nullable String user;

    @CustomType.Constructor
    private IntegrationActionCreate(
        @CustomType.Parameter("alertActions") @Nullable List<String> alertActions,
        @CustomType.Parameter("alias") @Nullable String alias,
        @CustomType.Parameter("appendAttachments") @Nullable Boolean appendAttachments,
        @CustomType.Parameter("customPriority") @Nullable String customPriority,
        @CustomType.Parameter("description") @Nullable String description,
        @CustomType.Parameter("entity") @Nullable String entity,
        @CustomType.Parameter("extraProperties") @Nullable Map<String,String> extraProperties,
        @CustomType.Parameter("filters") @Nullable List<IntegrationActionCreateFilter> filters,
        @CustomType.Parameter("ignoreAlertActionsFromPayload") @Nullable Boolean ignoreAlertActionsFromPayload,
        @CustomType.Parameter("ignoreExtraPropertiesFromPayload") @Nullable Boolean ignoreExtraPropertiesFromPayload,
        @CustomType.Parameter("ignoreRespondersFromPayload") @Nullable Boolean ignoreRespondersFromPayload,
        @CustomType.Parameter("ignoreTagsFromPayload") @Nullable Boolean ignoreTagsFromPayload,
        @CustomType.Parameter("ignoreTeamsFromPayload") @Nullable Boolean ignoreTeamsFromPayload,
        @CustomType.Parameter("message") @Nullable String message,
        @CustomType.Parameter("name") String name,
        @CustomType.Parameter("note") @Nullable String note,
        @CustomType.Parameter("order") @Nullable Integer order,
        @CustomType.Parameter("priority") @Nullable String priority,
        @CustomType.Parameter("responders") @Nullable List<IntegrationActionCreateResponder> responders,
        @CustomType.Parameter("source") @Nullable String source,
        @CustomType.Parameter("tags") @Nullable List<String> tags,
        @CustomType.Parameter("type") @Nullable String type,
        @CustomType.Parameter("user") @Nullable String user) {
        this.alertActions = alertActions;
        this.alias = alias;
        this.appendAttachments = appendAttachments;
        this.customPriority = customPriority;
        this.description = description;
        this.entity = entity;
        this.extraProperties = extraProperties;
        this.filters = filters;
        this.ignoreAlertActionsFromPayload = ignoreAlertActionsFromPayload;
        this.ignoreExtraPropertiesFromPayload = ignoreExtraPropertiesFromPayload;
        this.ignoreRespondersFromPayload = ignoreRespondersFromPayload;
        this.ignoreTagsFromPayload = ignoreTagsFromPayload;
        this.ignoreTeamsFromPayload = ignoreTeamsFromPayload;
        this.message = message;
        this.name = name;
        this.note = note;
        this.order = order;
        this.priority = priority;
        this.responders = responders;
        this.source = source;
        this.tags = tags;
        this.type = type;
        this.user = user;
    }

    public List<String> alertActions() {
        return this.alertActions == null ? List.of() : this.alertActions;
    }
    /**
     * @return An identifier that is used for alert deduplication. Default: `{{alias}}`.
     * 
     */
    public Optional<String> alias() {
        return Optional.ofNullable(this.alias);
    }
    public Optional<Boolean> appendAttachments() {
        return Optional.ofNullable(this.appendAttachments);
    }
    /**
     * @return Custom alert priority. e.g. ``{{message.substring(0,2)}}``
     * 
     */
    public Optional<String> customPriority() {
        return Optional.ofNullable(this.customPriority);
    }
    /**
     * @return Detailed description of the alert, anything that may not have fit in the `message` field.
     * 
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }
    /**
     * @return The entity the alert is related to.
     * 
     */
    public Optional<String> entity() {
        return Optional.ofNullable(this.entity);
    }
    /**
     * @return Set of user defined properties specified as a map.
     * 
     */
    public Map<String,String> extraProperties() {
        return this.extraProperties == null ? Map.of() : this.extraProperties;
    }
    /**
     * @return Used to specify rules for matching alerts and the filter type. Please note that depending on the integration type the field names in the filter conditions are:
     * * For SNS integration: `actions`, `alias`, `entity`, `Message`, `recipients`, `responders`, `Subject`, `tags`, `teams`, `eventType`, `Timestamp`, `TopicArn`.
     * * For API integration: `message`, `alias`, `description`, `source`, `entity`, `tags`, `actions`, `details`, `extra-properties`, `recipients`, `teams`, `priority`, `eventType`.
     * * For Email integration: `from_address`, `from_name`, `conversationSubject`, `subject`
     * 
     */
    public List<IntegrationActionCreateFilter> filters() {
        return this.filters == null ? List.of() : this.filters;
    }
    public Optional<Boolean> ignoreAlertActionsFromPayload() {
        return Optional.ofNullable(this.ignoreAlertActionsFromPayload);
    }
    public Optional<Boolean> ignoreExtraPropertiesFromPayload() {
        return Optional.ofNullable(this.ignoreExtraPropertiesFromPayload);
    }
    /**
     * @return If enabled, the integration will ignore responders sent in request payloads.
     * 
     */
    public Optional<Boolean> ignoreRespondersFromPayload() {
        return Optional.ofNullable(this.ignoreRespondersFromPayload);
    }
    public Optional<Boolean> ignoreTagsFromPayload() {
        return Optional.ofNullable(this.ignoreTagsFromPayload);
    }
    /**
     * @return If enabled, the integration will ignore teams sent in request payloads.
     * 
     */
    public Optional<Boolean> ignoreTeamsFromPayload() {
        return Optional.ofNullable(this.ignoreTeamsFromPayload);
    }
    /**
     * @return Alert text limited to 130 characters.
     * 
     */
    public Optional<String> message() {
        return Optional.ofNullable(this.message);
    }
    /**
     * @return Name of the integration action.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Additional alert action note.
     * 
     */
    public Optional<String> note() {
        return Optional.ofNullable(this.note);
    }
    /**
     * @return Integer value that defines in which order the action will be performed. Default: `1`.
     * 
     */
    public Optional<Integer> order() {
        return Optional.ofNullable(this.order);
    }
    /**
     * @return Alert priority.
     * 
     */
    public Optional<String> priority() {
        return Optional.ofNullable(this.priority);
    }
    /**
     * @return User, schedule, teams or escalation names to calculate which users will receive notifications of the alert.
     * 
     */
    public List<IntegrationActionCreateResponder> responders() {
        return this.responders == null ? List.of() : this.responders;
    }
    /**
     * @return User defined field to specify source of action.
     * 
     */
    public Optional<String> source() {
        return Optional.ofNullable(this.source);
    }
    /**
     * @return Comma separated list of labels to be attached to the alert.
     * 
     */
    public List<String> tags() {
        return this.tags == null ? List.of() : this.tags;
    }
    /**
     * @return The responder type - can be `escalation`, `team` or `user`.
     * 
     */
    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }
    /**
     * @return Owner of the execution for integration action.
     * 
     */
    public Optional<String> user() {
        return Optional.ofNullable(this.user);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(IntegrationActionCreate defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable List<String> alertActions;
        private @Nullable String alias;
        private @Nullable Boolean appendAttachments;
        private @Nullable String customPriority;
        private @Nullable String description;
        private @Nullable String entity;
        private @Nullable Map<String,String> extraProperties;
        private @Nullable List<IntegrationActionCreateFilter> filters;
        private @Nullable Boolean ignoreAlertActionsFromPayload;
        private @Nullable Boolean ignoreExtraPropertiesFromPayload;
        private @Nullable Boolean ignoreRespondersFromPayload;
        private @Nullable Boolean ignoreTagsFromPayload;
        private @Nullable Boolean ignoreTeamsFromPayload;
        private @Nullable String message;
        private String name;
        private @Nullable String note;
        private @Nullable Integer order;
        private @Nullable String priority;
        private @Nullable List<IntegrationActionCreateResponder> responders;
        private @Nullable String source;
        private @Nullable List<String> tags;
        private @Nullable String type;
        private @Nullable String user;

        public Builder() {
    	      // Empty
        }

        public Builder(IntegrationActionCreate defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.alertActions = defaults.alertActions;
    	      this.alias = defaults.alias;
    	      this.appendAttachments = defaults.appendAttachments;
    	      this.customPriority = defaults.customPriority;
    	      this.description = defaults.description;
    	      this.entity = defaults.entity;
    	      this.extraProperties = defaults.extraProperties;
    	      this.filters = defaults.filters;
    	      this.ignoreAlertActionsFromPayload = defaults.ignoreAlertActionsFromPayload;
    	      this.ignoreExtraPropertiesFromPayload = defaults.ignoreExtraPropertiesFromPayload;
    	      this.ignoreRespondersFromPayload = defaults.ignoreRespondersFromPayload;
    	      this.ignoreTagsFromPayload = defaults.ignoreTagsFromPayload;
    	      this.ignoreTeamsFromPayload = defaults.ignoreTeamsFromPayload;
    	      this.message = defaults.message;
    	      this.name = defaults.name;
    	      this.note = defaults.note;
    	      this.order = defaults.order;
    	      this.priority = defaults.priority;
    	      this.responders = defaults.responders;
    	      this.source = defaults.source;
    	      this.tags = defaults.tags;
    	      this.type = defaults.type;
    	      this.user = defaults.user;
        }

        public Builder alertActions(@Nullable List<String> alertActions) {
            this.alertActions = alertActions;
            return this;
        }
        public Builder alertActions(String... alertActions) {
            return alertActions(List.of(alertActions));
        }
        public Builder alias(@Nullable String alias) {
            this.alias = alias;
            return this;
        }
        public Builder appendAttachments(@Nullable Boolean appendAttachments) {
            this.appendAttachments = appendAttachments;
            return this;
        }
        public Builder customPriority(@Nullable String customPriority) {
            this.customPriority = customPriority;
            return this;
        }
        public Builder description(@Nullable String description) {
            this.description = description;
            return this;
        }
        public Builder entity(@Nullable String entity) {
            this.entity = entity;
            return this;
        }
        public Builder extraProperties(@Nullable Map<String,String> extraProperties) {
            this.extraProperties = extraProperties;
            return this;
        }
        public Builder filters(@Nullable List<IntegrationActionCreateFilter> filters) {
            this.filters = filters;
            return this;
        }
        public Builder filters(IntegrationActionCreateFilter... filters) {
            return filters(List.of(filters));
        }
        public Builder ignoreAlertActionsFromPayload(@Nullable Boolean ignoreAlertActionsFromPayload) {
            this.ignoreAlertActionsFromPayload = ignoreAlertActionsFromPayload;
            return this;
        }
        public Builder ignoreExtraPropertiesFromPayload(@Nullable Boolean ignoreExtraPropertiesFromPayload) {
            this.ignoreExtraPropertiesFromPayload = ignoreExtraPropertiesFromPayload;
            return this;
        }
        public Builder ignoreRespondersFromPayload(@Nullable Boolean ignoreRespondersFromPayload) {
            this.ignoreRespondersFromPayload = ignoreRespondersFromPayload;
            return this;
        }
        public Builder ignoreTagsFromPayload(@Nullable Boolean ignoreTagsFromPayload) {
            this.ignoreTagsFromPayload = ignoreTagsFromPayload;
            return this;
        }
        public Builder ignoreTeamsFromPayload(@Nullable Boolean ignoreTeamsFromPayload) {
            this.ignoreTeamsFromPayload = ignoreTeamsFromPayload;
            return this;
        }
        public Builder message(@Nullable String message) {
            this.message = message;
            return this;
        }
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        public Builder note(@Nullable String note) {
            this.note = note;
            return this;
        }
        public Builder order(@Nullable Integer order) {
            this.order = order;
            return this;
        }
        public Builder priority(@Nullable String priority) {
            this.priority = priority;
            return this;
        }
        public Builder responders(@Nullable List<IntegrationActionCreateResponder> responders) {
            this.responders = responders;
            return this;
        }
        public Builder responders(IntegrationActionCreateResponder... responders) {
            return responders(List.of(responders));
        }
        public Builder source(@Nullable String source) {
            this.source = source;
            return this;
        }
        public Builder tags(@Nullable List<String> tags) {
            this.tags = tags;
            return this;
        }
        public Builder tags(String... tags) {
            return tags(List.of(tags));
        }
        public Builder type(@Nullable String type) {
            this.type = type;
            return this;
        }
        public Builder user(@Nullable String user) {
            this.user = user;
            return this;
        }        public IntegrationActionCreate build() {
            return new IntegrationActionCreate(alertActions, alias, appendAttachments, customPriority, description, entity, extraProperties, filters, ignoreAlertActionsFromPayload, ignoreExtraPropertiesFromPayload, ignoreRespondersFromPayload, ignoreTagsFromPayload, ignoreTeamsFromPayload, message, name, note, order, priority, responders, source, tags, type, user);
        }
    }
}
