// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.opsgenie.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class IntegrationActionAcknowledgeFilterCondition {
    private @Nullable String expectedValue;
    private String field;
    private @Nullable String key;
    private @Nullable Boolean not;
    private String operation;
    /**
     * @return Integer value that defines in which order the action will be performed. Default: `1`.
     * 
     */
    private @Nullable Integer order;

    private IntegrationActionAcknowledgeFilterCondition() {}
    public Optional<String> expectedValue() {
        return Optional.ofNullable(this.expectedValue);
    }
    public String field() {
        return this.field;
    }
    public Optional<String> key() {
        return Optional.ofNullable(this.key);
    }
    public Optional<Boolean> not() {
        return Optional.ofNullable(this.not);
    }
    public String operation() {
        return this.operation;
    }
    /**
     * @return Integer value that defines in which order the action will be performed. Default: `1`.
     * 
     */
    public Optional<Integer> order() {
        return Optional.ofNullable(this.order);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(IntegrationActionAcknowledgeFilterCondition defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String expectedValue;
        private String field;
        private @Nullable String key;
        private @Nullable Boolean not;
        private String operation;
        private @Nullable Integer order;
        public Builder() {}
        public Builder(IntegrationActionAcknowledgeFilterCondition defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.expectedValue = defaults.expectedValue;
    	      this.field = defaults.field;
    	      this.key = defaults.key;
    	      this.not = defaults.not;
    	      this.operation = defaults.operation;
    	      this.order = defaults.order;
        }

        @CustomType.Setter
        public Builder expectedValue(@Nullable String expectedValue) {
            this.expectedValue = expectedValue;
            return this;
        }
        @CustomType.Setter
        public Builder field(String field) {
            this.field = Objects.requireNonNull(field);
            return this;
        }
        @CustomType.Setter
        public Builder key(@Nullable String key) {
            this.key = key;
            return this;
        }
        @CustomType.Setter
        public Builder not(@Nullable Boolean not) {
            this.not = not;
            return this;
        }
        @CustomType.Setter
        public Builder operation(String operation) {
            this.operation = Objects.requireNonNull(operation);
            return this;
        }
        @CustomType.Setter
        public Builder order(@Nullable Integer order) {
            this.order = order;
            return this;
        }
        public IntegrationActionAcknowledgeFilterCondition build() {
            final var o = new IntegrationActionAcknowledgeFilterCondition();
            o.expectedValue = expectedValue;
            o.field = field;
            o.key = key;
            o.not = not;
            o.operation = operation;
            o.order = order;
            return o;
        }
    }
}
