// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.opsgenie.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.opsgenie.outputs.NotificationPolicyTimeRestrictionRestriction;
import com.pulumi.opsgenie.outputs.NotificationPolicyTimeRestrictionRestrictionList;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class NotificationPolicyTimeRestriction {
    /**
     * @return A definition of hourly definition applied daily, this has to be used with combination: type = `time-of-day`. This is a block, structure is documented below.
     * 
     */
    private @Nullable List<NotificationPolicyTimeRestrictionRestriction> restriction;
    /**
     * @return List of days and hours definitions for field type = `weekday-and-time-of-day`. This is a block, structure is documented below.
     * 
     */
    private @Nullable List<NotificationPolicyTimeRestrictionRestrictionList> restrictionList;
    /**
     * @return Defines if restriction should apply daily on given hours or on certain days and hours. Possible values are: `time-of-day`, `weekday-and-time-of-day`
     * 
     */
    private String type;

    private NotificationPolicyTimeRestriction() {}
    /**
     * @return A definition of hourly definition applied daily, this has to be used with combination: type = `time-of-day`. This is a block, structure is documented below.
     * 
     */
    public List<NotificationPolicyTimeRestrictionRestriction> restriction() {
        return this.restriction == null ? List.of() : this.restriction;
    }
    /**
     * @return List of days and hours definitions for field type = `weekday-and-time-of-day`. This is a block, structure is documented below.
     * 
     */
    public List<NotificationPolicyTimeRestrictionRestrictionList> restrictionList() {
        return this.restrictionList == null ? List.of() : this.restrictionList;
    }
    /**
     * @return Defines if restriction should apply daily on given hours or on certain days and hours. Possible values are: `time-of-day`, `weekday-and-time-of-day`
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NotificationPolicyTimeRestriction defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<NotificationPolicyTimeRestrictionRestriction> restriction;
        private @Nullable List<NotificationPolicyTimeRestrictionRestrictionList> restrictionList;
        private String type;
        public Builder() {}
        public Builder(NotificationPolicyTimeRestriction defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.restriction = defaults.restriction;
    	      this.restrictionList = defaults.restrictionList;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder restriction(@Nullable List<NotificationPolicyTimeRestrictionRestriction> restriction) {

            this.restriction = restriction;
            return this;
        }
        public Builder restriction(NotificationPolicyTimeRestrictionRestriction... restriction) {
            return restriction(List.of(restriction));
        }
        @CustomType.Setter
        public Builder restrictionList(@Nullable List<NotificationPolicyTimeRestrictionRestrictionList> restrictionList) {

            this.restrictionList = restrictionList;
            return this;
        }
        public Builder restrictionList(NotificationPolicyTimeRestrictionRestrictionList... restrictionList) {
            return restrictionList(List.of(restrictionList));
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("NotificationPolicyTimeRestriction", "type");
            }
            this.type = type;
            return this;
        }
        public NotificationPolicyTimeRestriction build() {
            final var _resultValue = new NotificationPolicyTimeRestriction();
            _resultValue.restriction = restriction;
            _resultValue.restrictionList = restrictionList;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
