// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.opsgenie.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.opsgenie.outputs.NotificationPolicyAutoRestartActionDuration;
import java.lang.Integer;
import java.util.List;
import java.util.Objects;

@CustomType
public final class NotificationPolicyAutoRestartAction {
    /**
     * @return Duration of this action. This is a block, structure is documented below.
     * 
     */
    private List<NotificationPolicyAutoRestartActionDuration> durations;
    /**
     * @return How many times to repeat. This is a integer attribute.
     * 
     */
    private Integer maxRepeatCount;

    private NotificationPolicyAutoRestartAction() {}
    /**
     * @return Duration of this action. This is a block, structure is documented below.
     * 
     */
    public List<NotificationPolicyAutoRestartActionDuration> durations() {
        return this.durations;
    }
    /**
     * @return How many times to repeat. This is a integer attribute.
     * 
     */
    public Integer maxRepeatCount() {
        return this.maxRepeatCount;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NotificationPolicyAutoRestartAction defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<NotificationPolicyAutoRestartActionDuration> durations;
        private Integer maxRepeatCount;
        public Builder() {}
        public Builder(NotificationPolicyAutoRestartAction defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.durations = defaults.durations;
    	      this.maxRepeatCount = defaults.maxRepeatCount;
        }

        @CustomType.Setter
        public Builder durations(List<NotificationPolicyAutoRestartActionDuration> durations) {
            if (durations == null) {
              throw new MissingRequiredPropertyException("NotificationPolicyAutoRestartAction", "durations");
            }
            this.durations = durations;
            return this;
        }
        public Builder durations(NotificationPolicyAutoRestartActionDuration... durations) {
            return durations(List.of(durations));
        }
        @CustomType.Setter
        public Builder maxRepeatCount(Integer maxRepeatCount) {
            if (maxRepeatCount == null) {
              throw new MissingRequiredPropertyException("NotificationPolicyAutoRestartAction", "maxRepeatCount");
            }
            this.maxRepeatCount = maxRepeatCount;
            return this;
        }
        public NotificationPolicyAutoRestartAction build() {
            final var _resultValue = new NotificationPolicyAutoRestartAction();
            _resultValue.durations = durations;
            _resultValue.maxRepeatCount = maxRepeatCount;
            return _resultValue;
        }
    }
}
