// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.opsgenie.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;

@CustomType
public final class ScheduleRotationTimeRestrictionRestriction {
    private Integer endHour;
    private Integer endMin;
    private Integer startHour;
    private Integer startMin;

    private ScheduleRotationTimeRestrictionRestriction() {}
    public Integer endHour() {
        return this.endHour;
    }
    public Integer endMin() {
        return this.endMin;
    }
    public Integer startHour() {
        return this.startHour;
    }
    public Integer startMin() {
        return this.startMin;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ScheduleRotationTimeRestrictionRestriction defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer endHour;
        private Integer endMin;
        private Integer startHour;
        private Integer startMin;
        public Builder() {}
        public Builder(ScheduleRotationTimeRestrictionRestriction defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.endHour = defaults.endHour;
    	      this.endMin = defaults.endMin;
    	      this.startHour = defaults.startHour;
    	      this.startMin = defaults.startMin;
        }

        @CustomType.Setter
        public Builder endHour(Integer endHour) {
            if (endHour == null) {
              throw new MissingRequiredPropertyException("ScheduleRotationTimeRestrictionRestriction", "endHour");
            }
            this.endHour = endHour;
            return this;
        }
        @CustomType.Setter
        public Builder endMin(Integer endMin) {
            if (endMin == null) {
              throw new MissingRequiredPropertyException("ScheduleRotationTimeRestrictionRestriction", "endMin");
            }
            this.endMin = endMin;
            return this;
        }
        @CustomType.Setter
        public Builder startHour(Integer startHour) {
            if (startHour == null) {
              throw new MissingRequiredPropertyException("ScheduleRotationTimeRestrictionRestriction", "startHour");
            }
            this.startHour = startHour;
            return this;
        }
        @CustomType.Setter
        public Builder startMin(Integer startMin) {
            if (startMin == null) {
              throw new MissingRequiredPropertyException("ScheduleRotationTimeRestrictionRestriction", "startMin");
            }
            this.startMin = startMin;
            return this;
        }
        public ScheduleRotationTimeRestrictionRestriction build() {
            final var _resultValue = new ScheduleRotationTimeRestrictionRestriction();
            _resultValue.endHour = endHour;
            _resultValue.endMin = endMin;
            _resultValue.startHour = startHour;
            _resultValue.startMin = startMin;
            return _resultValue;
        }
    }
}
