// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.opsgenie.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class TeamRoutingRuleTimeRestrictionRestrictionList {
    private String endDay;
    private Integer endHour;
    private Integer endMin;
    private String startDay;
    private Integer startHour;
    private Integer startMin;

    private TeamRoutingRuleTimeRestrictionRestrictionList() {}
    public String endDay() {
        return this.endDay;
    }
    public Integer endHour() {
        return this.endHour;
    }
    public Integer endMin() {
        return this.endMin;
    }
    public String startDay() {
        return this.startDay;
    }
    public Integer startHour() {
        return this.startHour;
    }
    public Integer startMin() {
        return this.startMin;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(TeamRoutingRuleTimeRestrictionRestrictionList defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String endDay;
        private Integer endHour;
        private Integer endMin;
        private String startDay;
        private Integer startHour;
        private Integer startMin;
        public Builder() {}
        public Builder(TeamRoutingRuleTimeRestrictionRestrictionList defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.endDay = defaults.endDay;
    	      this.endHour = defaults.endHour;
    	      this.endMin = defaults.endMin;
    	      this.startDay = defaults.startDay;
    	      this.startHour = defaults.startHour;
    	      this.startMin = defaults.startMin;
        }

        @CustomType.Setter
        public Builder endDay(String endDay) {
            if (endDay == null) {
              throw new MissingRequiredPropertyException("TeamRoutingRuleTimeRestrictionRestrictionList", "endDay");
            }
            this.endDay = endDay;
            return this;
        }
        @CustomType.Setter
        public Builder endHour(Integer endHour) {
            if (endHour == null) {
              throw new MissingRequiredPropertyException("TeamRoutingRuleTimeRestrictionRestrictionList", "endHour");
            }
            this.endHour = endHour;
            return this;
        }
        @CustomType.Setter
        public Builder endMin(Integer endMin) {
            if (endMin == null) {
              throw new MissingRequiredPropertyException("TeamRoutingRuleTimeRestrictionRestrictionList", "endMin");
            }
            this.endMin = endMin;
            return this;
        }
        @CustomType.Setter
        public Builder startDay(String startDay) {
            if (startDay == null) {
              throw new MissingRequiredPropertyException("TeamRoutingRuleTimeRestrictionRestrictionList", "startDay");
            }
            this.startDay = startDay;
            return this;
        }
        @CustomType.Setter
        public Builder startHour(Integer startHour) {
            if (startHour == null) {
              throw new MissingRequiredPropertyException("TeamRoutingRuleTimeRestrictionRestrictionList", "startHour");
            }
            this.startHour = startHour;
            return this;
        }
        @CustomType.Setter
        public Builder startMin(Integer startMin) {
            if (startMin == null) {
              throw new MissingRequiredPropertyException("TeamRoutingRuleTimeRestrictionRestrictionList", "startMin");
            }
            this.startMin = startMin;
            return this;
        }
        public TeamRoutingRuleTimeRestrictionRestrictionList build() {
            final var _resultValue = new TeamRoutingRuleTimeRestrictionRestrictionList();
            _resultValue.endDay = endDay;
            _resultValue.endHour = endHour;
            _resultValue.endMin = endMin;
            _resultValue.startDay = startDay;
            _resultValue.startHour = startHour;
            _resultValue.startMin = startMin;
            return _resultValue;
        }
    }
}
