// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.opsgenie.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.opsgenie.outputs.TeamRoutingRuleTimeRestrictionRestriction;
import com.pulumi.opsgenie.outputs.TeamRoutingRuleTimeRestrictionRestrictionList;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class TeamRoutingRuleTimeRestriction {
    private final @Nullable List<TeamRoutingRuleTimeRestrictionRestriction> restriction;
    private final @Nullable List<TeamRoutingRuleTimeRestrictionRestrictionList> restrictionList;
    private final String type;

    @CustomType.Constructor
    private TeamRoutingRuleTimeRestriction(
        @CustomType.Parameter("restriction") @Nullable List<TeamRoutingRuleTimeRestrictionRestriction> restriction,
        @CustomType.Parameter("restrictionList") @Nullable List<TeamRoutingRuleTimeRestrictionRestrictionList> restrictionList,
        @CustomType.Parameter("type") String type) {
        this.restriction = restriction;
        this.restrictionList = restrictionList;
        this.type = type;
    }

    public List<TeamRoutingRuleTimeRestrictionRestriction> restriction() {
        return this.restriction == null ? List.of() : this.restriction;
    }
    public List<TeamRoutingRuleTimeRestrictionRestrictionList> restrictionList() {
        return this.restrictionList == null ? List.of() : this.restrictionList;
    }
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(TeamRoutingRuleTimeRestriction defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable List<TeamRoutingRuleTimeRestrictionRestriction> restriction;
        private @Nullable List<TeamRoutingRuleTimeRestrictionRestrictionList> restrictionList;
        private String type;

        public Builder() {
    	      // Empty
        }

        public Builder(TeamRoutingRuleTimeRestriction defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.restriction = defaults.restriction;
    	      this.restrictionList = defaults.restrictionList;
    	      this.type = defaults.type;
        }

        public Builder restriction(@Nullable List<TeamRoutingRuleTimeRestrictionRestriction> restriction) {
            this.restriction = restriction;
            return this;
        }
        public Builder restriction(TeamRoutingRuleTimeRestrictionRestriction... restriction) {
            return restriction(List.of(restriction));
        }
        public Builder restrictionList(@Nullable List<TeamRoutingRuleTimeRestrictionRestrictionList> restrictionList) {
            this.restrictionList = restrictionList;
            return this;
        }
        public Builder restrictionList(TeamRoutingRuleTimeRestrictionRestrictionList... restrictionList) {
            return restrictionList(List.of(restrictionList));
        }
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }        public TeamRoutingRuleTimeRestriction build() {
            return new TeamRoutingRuleTimeRestriction(restriction, restrictionList, type);
        }
    }
}
