// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Opsgenie.Outputs
{

    [OutputType]
    public sealed class MaintenanceTime
    {
        /// <summary>
        /// This parameter takes a date format as (yyyy-MM-dd'T'HH:mm:ssZ) (e.g. 2019-06-11T08:00:00+02:00).
        /// </summary>
        public readonly string? EndDate;
        /// <summary>
        /// This parameter takes a date format as (yyyy-MM-dd'T'HH:mm:ssZ) (e.g. 2019-06-11T08:00:00+02:00).
        /// </summary>
        public readonly string? StartDate;
        /// <summary>
        /// This parameter defines when the maintenance will be active. It can take one of for-5-minutes, for-30-minutes, for-1-hour, indefinitely or schedule.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private MaintenanceTime(
            string? endDate,

            string? startDate,

            string type)
        {
            EndDate = endDate;
            StartDate = startDate;
            Type = type;
        }
    }
}
