// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Opsgenie.Outputs
{

    [OutputType]
    public sealed class NotificationRuleStepContact
    {
        /// <summary>
        /// Contact method. Possible values: `email`, `sms`, `voice`, `mobile`
        /// </summary>
        public readonly string Method;
        /// <summary>
        /// Address of a given method (eg. email address for `email`, phone number for `sms`/`voice` or mobile application name for `mobile`)
        /// </summary>
        public readonly string To;

        [OutputConstructor]
        private NotificationRuleStepContact(
            string method,

            string to)
        {
            Method = method;
            To = to;
        }
    }
}
