// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Opsgenie.Outputs
{

    [OutputType]
    public sealed class NotificationPolicyTimeRestrictionRestriction
    {
        /// <summary>
        /// Ending hour of restriction.
        /// </summary>
        public readonly int EndHour;
        /// <summary>
        /// Ending minute of restriction on defined `end_hour`
        /// </summary>
        public readonly int EndMin;
        /// <summary>
        /// Starting hour of restriction.
        /// </summary>
        public readonly int StartHour;
        /// <summary>
        /// Staring minute of restriction on defined `start_hour`
        /// </summary>
        public readonly int StartMin;

        [OutputConstructor]
        private NotificationPolicyTimeRestrictionRestriction(
            int endHour,

            int endMin,

            int startHour,

            int startMin)
        {
            EndHour = endHour;
            EndMin = endMin;
            StartHour = startHour;
            StartMin = startMin;
        }
    }
}
