// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.opsgenie.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.opsgenie.inputs.GetTeamMember;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetTeamPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetTeamPlainArgs Empty = new GetTeamPlainArgs();

    /**
     * A description for this team.
     * 
     */
    @Import(name="description")
    private @Nullable String description;

    /**
     * @return A description for this team.
     * 
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * A Member block as documented below.
     * 
     */
    @Import(name="members")
    private @Nullable List<GetTeamMember> members;

    /**
     * @return A Member block as documented below.
     * 
     */
    public Optional<List<GetTeamMember>> members() {
        return Optional.ofNullable(this.members);
    }

    /**
     * The name associated with this team. Opsgenie defines that this must not be longer than 100 characters.
     * 
     */
    @Import(name="name", required=true)
    private String name;

    /**
     * @return The name associated with this team. Opsgenie defines that this must not be longer than 100 characters.
     * 
     */
    public String name() {
        return this.name;
    }

    private GetTeamPlainArgs() {}

    private GetTeamPlainArgs(GetTeamPlainArgs $) {
        this.description = $.description;
        this.members = $.members;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetTeamPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetTeamPlainArgs $;

        public Builder() {
            $ = new GetTeamPlainArgs();
        }

        public Builder(GetTeamPlainArgs defaults) {
            $ = new GetTeamPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param description A description for this team.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable String description) {
            $.description = description;
            return this;
        }

        /**
         * @param members A Member block as documented below.
         * 
         * @return builder
         * 
         */
        public Builder members(@Nullable List<GetTeamMember> members) {
            $.members = members;
            return this;
        }

        /**
         * @param members A Member block as documented below.
         * 
         * @return builder
         * 
         */
        public Builder members(GetTeamMember... members) {
            return members(List.of(members));
        }

        /**
         * @param name The name associated with this team. Opsgenie defines that this must not be longer than 100 characters.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            $.name = name;
            return this;
        }

        public GetTeamPlainArgs build() {
            $.name = Objects.requireNonNull($.name, "expected parameter 'name' to be non-null");
            return $;
        }
    }

}
