// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.opsgenie.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class IntegrationActionCreateResponderArgs extends com.pulumi.resources.ResourceArgs {

    public static final IntegrationActionCreateResponderArgs Empty = new IntegrationActionCreateResponderArgs();

    /**
     * The id of the responder.
     * 
     */
    @Import(name="id", required=true)
    private Output<String> id;

    /**
     * @return The id of the responder.
     * 
     */
    public Output<String> id() {
        return this.id;
    }

    /**
     * The responder type - can be `escalation`, `team` or `user`.
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return The responder type - can be `escalation`, `team` or `user`.
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    private IntegrationActionCreateResponderArgs() {}

    private IntegrationActionCreateResponderArgs(IntegrationActionCreateResponderArgs $) {
        this.id = $.id;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IntegrationActionCreateResponderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IntegrationActionCreateResponderArgs $;

        public Builder() {
            $ = new IntegrationActionCreateResponderArgs();
        }

        public Builder(IntegrationActionCreateResponderArgs defaults) {
            $ = new IntegrationActionCreateResponderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The id of the responder.
         * 
         * @return builder
         * 
         */
        public Builder id(Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id The id of the responder.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        /**
         * @param type The responder type - can be `escalation`, `team` or `user`.
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type The responder type - can be `escalation`, `team` or `user`.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public IntegrationActionCreateResponderArgs build() {
            $.id = Objects.requireNonNull($.id, "expected parameter 'id' to be non-null");
            $.type = Objects.requireNonNull($.type, "expected parameter 'type' to be non-null");
            return $;
        }
    }

}
