// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Escalation extends pulumi.CustomResource {
    /**
     * Get an existing Escalation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EscalationState, opts?: pulumi.CustomResourceOptions): Escalation {
        return new Escalation(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'opsgenie:index/escalation:Escalation';

    /**
     * Returns true if the given object is an instance of Escalation.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Escalation {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Escalation.__pulumiType;
    }

    public readonly description!: pulumi.Output<string | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly ownerTeamId!: pulumi.Output<string | undefined>;
    public readonly repeats!: pulumi.Output<outputs.EscalationRepeat[] | undefined>;
    public readonly rules!: pulumi.Output<outputs.EscalationRule[]>;

    /**
     * Create a Escalation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EscalationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EscalationArgs | EscalationState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as EscalationState | undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["ownerTeamId"] = state ? state.ownerTeamId : undefined;
            inputs["repeats"] = state ? state.repeats : undefined;
            inputs["rules"] = state ? state.rules : undefined;
        } else {
            const args = argsOrState as EscalationArgs | undefined;
            if (!args || args.rules === undefined) {
                throw new Error("Missing required property 'rules'");
            }
            inputs["description"] = args ? args.description : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["ownerTeamId"] = args ? args.ownerTeamId : undefined;
            inputs["repeats"] = args ? args.repeats : undefined;
            inputs["rules"] = args ? args.rules : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(Escalation.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Escalation resources.
 */
export interface EscalationState {
    readonly description?: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly ownerTeamId?: pulumi.Input<string>;
    readonly repeats?: pulumi.Input<pulumi.Input<inputs.EscalationRepeat>[]>;
    readonly rules?: pulumi.Input<pulumi.Input<inputs.EscalationRule>[]>;
}

/**
 * The set of arguments for constructing a Escalation resource.
 */
export interface EscalationArgs {
    readonly description?: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly ownerTeamId?: pulumi.Input<string>;
    readonly repeats?: pulumi.Input<pulumi.Input<inputs.EscalationRepeat>[]>;
    readonly rules: pulumi.Input<pulumi.Input<inputs.EscalationRule>[]>;
}
