// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Maintenance extends pulumi.CustomResource {
    /**
     * Get an existing Maintenance resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MaintenanceState, opts?: pulumi.CustomResourceOptions): Maintenance {
        return new Maintenance(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'opsgenie:index/maintenance:Maintenance';

    /**
     * Returns true if the given object is an instance of Maintenance.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Maintenance {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Maintenance.__pulumiType;
    }

    public readonly description!: pulumi.Output<string>;
    public readonly rules!: pulumi.Output<outputs.MaintenanceRule[]>;
    public readonly times!: pulumi.Output<outputs.MaintenanceTime[] | undefined>;

    /**
     * Create a Maintenance resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MaintenanceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MaintenanceArgs | MaintenanceState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as MaintenanceState | undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["rules"] = state ? state.rules : undefined;
            inputs["times"] = state ? state.times : undefined;
        } else {
            const args = argsOrState as MaintenanceArgs | undefined;
            if (!args || args.description === undefined) {
                throw new Error("Missing required property 'description'");
            }
            if (!args || args.rules === undefined) {
                throw new Error("Missing required property 'rules'");
            }
            inputs["description"] = args ? args.description : undefined;
            inputs["rules"] = args ? args.rules : undefined;
            inputs["times"] = args ? args.times : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(Maintenance.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Maintenance resources.
 */
export interface MaintenanceState {
    readonly description?: pulumi.Input<string>;
    readonly rules?: pulumi.Input<pulumi.Input<inputs.MaintenanceRule>[]>;
    readonly times?: pulumi.Input<pulumi.Input<inputs.MaintenanceTime>[]>;
}

/**
 * The set of arguments for constructing a Maintenance resource.
 */
export interface MaintenanceArgs {
    readonly description: pulumi.Input<string>;
    readonly rules: pulumi.Input<pulumi.Input<inputs.MaintenanceRule>[]>;
    readonly times?: pulumi.Input<pulumi.Input<inputs.MaintenanceTime>[]>;
}
