// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Opsgenie.Inputs
{

    public sealed class AlertPolicyTimeRestrictionRestrictionListGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Ending day of restriction (eg. `Wednesday`)
        /// </summary>
        [Input("endDay", required: true)]
        public Input<string> EndDay { get; set; } = null!;

        /// <summary>
        /// Ending hour of restriction on defined `EndDay`
        /// </summary>
        [Input("endHour", required: true)]
        public Input<int> EndHour { get; set; } = null!;

        /// <summary>
        /// Ending minute of restriction on defined `EndHour`
        /// </summary>
        [Input("endMin", required: true)]
        public Input<int> EndMin { get; set; } = null!;

        /// <summary>
        /// Starting day of restriction (eg. `Monday`)
        /// </summary>
        [Input("startDay", required: true)]
        public Input<string> StartDay { get; set; } = null!;

        /// <summary>
        /// Starting hour of restriction on defined `StartDay`
        /// </summary>
        [Input("startHour", required: true)]
        public Input<int> StartHour { get; set; } = null!;

        /// <summary>
        /// Staring minute of restriction on defined `StartHour`
        /// </summary>
        [Input("startMin", required: true)]
        public Input<int> StartMin { get; set; } = null!;

        public AlertPolicyTimeRestrictionRestrictionListGetArgs()
        {
        }
        public static new AlertPolicyTimeRestrictionRestrictionListGetArgs Empty => new AlertPolicyTimeRestrictionRestrictionListGetArgs();
    }
}
