// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Opsgenie.Inputs
{

    public sealed class GetEscalationRuleRecipientInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the Opsgenie Escalation.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public GetEscalationRuleRecipientInputArgs()
        {
        }
        public static new GetEscalationRuleRecipientInputArgs Empty => new GetEscalationRuleRecipientInputArgs();
    }
}
