// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Opsgenie.Inputs
{

    public sealed class MaintenanceTimeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// This parameter takes a date format as (yyyy-MM-dd'T'HH:mm:ssZ) (e.g. 2019-06-11T08:00:00+02:00).
        /// </summary>
        [Input("endDate")]
        public Input<string>? EndDate { get; set; }

        /// <summary>
        /// This parameter takes a date format as (yyyy-MM-dd'T'HH:mm:ssZ) (e.g. 2019-06-11T08:00:00+02:00).
        /// </summary>
        [Input("startDate")]
        public Input<string>? StartDate { get; set; }

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public MaintenanceTimeArgs()
        {
        }
        public static new MaintenanceTimeArgs Empty => new MaintenanceTimeArgs();
    }
}
