// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Opsgenie.Inputs
{

    public sealed class NotificationRuleScheduleGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the notification policy
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Kind of matching filter. Possible values: `match-all`, `match-any-condition`, `match-all-conditions`
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public NotificationRuleScheduleGetArgs()
        {
        }
        public static new NotificationRuleScheduleGetArgs Empty => new NotificationRuleScheduleGetArgs();
    }
}
