// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Opsgenie.Inputs
{

    public sealed class NotificationPolicyAutoRestartActionArgs : global::Pulumi.ResourceArgs
    {
        [Input("durations", required: true)]
        private InputList<Inputs.NotificationPolicyAutoRestartActionDurationArgs>? _durations;

        /// <summary>
        /// Duration of this action. This is a block, structure is documented below.
        /// </summary>
        public InputList<Inputs.NotificationPolicyAutoRestartActionDurationArgs> Durations
        {
            get => _durations ?? (_durations = new InputList<Inputs.NotificationPolicyAutoRestartActionDurationArgs>());
            set => _durations = value;
        }

        /// <summary>
        /// How many times to repeat. This is a integer attribute.
        /// </summary>
        [Input("maxRepeatCount", required: true)]
        public Input<int> MaxRepeatCount { get; set; } = null!;

        public NotificationPolicyAutoRestartActionArgs()
        {
        }
        public static new NotificationPolicyAutoRestartActionArgs Empty => new NotificationPolicyAutoRestartActionArgs();
    }
}
