// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Opsgenie.Inputs
{

    public sealed class NotificationRuleRepeatGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// If policy should be enabled. Default: `true`
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("loopAfter", required: true)]
        public Input<int> LoopAfter { get; set; } = null!;

        public NotificationRuleRepeatGetArgs()
        {
        }
        public static new NotificationRuleRepeatGetArgs Empty => new NotificationRuleRepeatGetArgs();
    }
}
