// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Opsgenie.Inputs
{

    public sealed class NotificationRuleCriteriaGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions")]
        private InputList<Inputs.NotificationRuleCriteriaConditionGetArgs>? _conditions;

        /// <summary>
        /// Defines the fields and values when the condition applies
        /// </summary>
        public InputList<Inputs.NotificationRuleCriteriaConditionGetArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Inputs.NotificationRuleCriteriaConditionGetArgs>());
            set => _conditions = value;
        }

        /// <summary>
        /// Kind of matching filter. Possible values: `match-all`, `match-any-condition`, `match-all-conditions`
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public NotificationRuleCriteriaGetArgs()
        {
        }
        public static new NotificationRuleCriteriaGetArgs Empty => new NotificationRuleCriteriaGetArgs();
    }
}
