// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.opsgenie;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class UserContactArgs extends com.pulumi.resources.ResourceArgs {

    public static final UserContactArgs Empty = new UserContactArgs();

    /**
     * Enable contact of the user in OpsGenie. Default value is true.
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return Enable contact of the user in OpsGenie. Default value is true.
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * This parameter is the contact method of user and should be one of email, sms or voice. Please note that adding mobile is not supported from API.
     * 
     */
    @Import(name="method", required=true)
    private Output<String> method;

    /**
     * @return This parameter is the contact method of user and should be one of email, sms or voice. Please note that adding mobile is not supported from API.
     * 
     */
    public Output<String> method() {
        return this.method;
    }

    /**
     * to field is the address of given method.
     * 
     */
    @Import(name="to", required=true)
    private Output<String> to;

    /**
     * @return to field is the address of given method.
     * 
     */
    public Output<String> to() {
        return this.to;
    }

    /**
     * The username for contact.(reference)
     * 
     */
    @Import(name="username", required=true)
    private Output<String> username;

    /**
     * @return The username for contact.(reference)
     * 
     */
    public Output<String> username() {
        return this.username;
    }

    private UserContactArgs() {}

    private UserContactArgs(UserContactArgs $) {
        this.enabled = $.enabled;
        this.method = $.method;
        this.to = $.to;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(UserContactArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private UserContactArgs $;

        public Builder() {
            $ = new UserContactArgs();
        }

        public Builder(UserContactArgs defaults) {
            $ = new UserContactArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param enabled Enable contact of the user in OpsGenie. Default value is true.
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Enable contact of the user in OpsGenie. Default value is true.
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param method This parameter is the contact method of user and should be one of email, sms or voice. Please note that adding mobile is not supported from API.
         * 
         * @return builder
         * 
         */
        public Builder method(Output<String> method) {
            $.method = method;
            return this;
        }

        /**
         * @param method This parameter is the contact method of user and should be one of email, sms or voice. Please note that adding mobile is not supported from API.
         * 
         * @return builder
         * 
         */
        public Builder method(String method) {
            return method(Output.of(method));
        }

        /**
         * @param to to field is the address of given method.
         * 
         * @return builder
         * 
         */
        public Builder to(Output<String> to) {
            $.to = to;
            return this;
        }

        /**
         * @param to to field is the address of given method.
         * 
         * @return builder
         * 
         */
        public Builder to(String to) {
            return to(Output.of(to));
        }

        /**
         * @param username The username for contact.(reference)
         * 
         * @return builder
         * 
         */
        public Builder username(Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username The username for contact.(reference)
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public UserContactArgs build() {
            if ($.method == null) {
                throw new MissingRequiredPropertyException("UserContactArgs", "method");
            }
            if ($.to == null) {
                throw new MissingRequiredPropertyException("UserContactArgs", "to");
            }
            if ($.username == null) {
                throw new MissingRequiredPropertyException("UserContactArgs", "username");
            }
            return $;
        }
    }

}
