// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * Manages an Escalation within Opsgenie.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as opsgenie from "@pulumi/opsgenie";
 *
 * const test = pulumi.output(opsgenie.getEscalation({
 *     name: "existing-escalation",
 * }, { async: true }));
 * ```
 */
export function getEscalation(args: GetEscalationArgs, opts?: pulumi.InvokeOptions): Promise<GetEscalationResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("opsgenie:index/getEscalation:getEscalation", {
        "description": args.description,
        "name": args.name,
        "ownerTeamId": args.ownerTeamId,
        "repeats": args.repeats,
        "rules": args.rules,
    }, opts);
}

/**
 * A collection of arguments for invoking getEscalation.
 */
export interface GetEscalationArgs {
    /**
     * Escalation Description
     */
    readonly description?: string;
    /**
     * Name of the escalation.
     */
    readonly name: string;
    /**
     * If owner team exist the id of the team is exported
     */
    readonly ownerTeamId?: string;
    /**
     * Escalation repeat preferences
     */
    readonly repeats?: inputs.GetEscalationRepeat[];
    /**
     * Escalation rules
     */
    readonly rules?: inputs.GetEscalationRule[];
}

/**
 * A collection of values returned by getEscalation.
 */
export interface GetEscalationResult {
    /**
     * Escalation Description
     */
    readonly description?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    /**
     * If owner team exist the id of the team is exported
     */
    readonly ownerTeamId?: string;
    /**
     * Escalation repeat preferences
     */
    readonly repeats?: outputs.GetEscalationRepeat[];
    /**
     * Escalation rules
     */
    readonly rules?: outputs.GetEscalationRule[];
}
