// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a Schedule within Opsgenie.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as opsgenie from "@pulumi/opsgenie";
 *
 * const test = opsgenie.getSchedule({
 *     name: "sre-team schedule",
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getSchedule(args: GetScheduleArgs, opts?: pulumi.InvokeOptions): Promise<GetScheduleResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("opsgenie:index/getSchedule:getSchedule", {
        "description": args.description,
        "enabled": args.enabled,
        "name": args.name,
        "ownerTeamId": args.ownerTeamId,
        "timezone": args.timezone,
    }, opts);
}

/**
 * A collection of arguments for invoking getSchedule.
 */
export interface GetScheduleArgs {
    /**
     * Timezone of schedule. Please look at [Supported Timezone Ids](https://docs.opsgenie.com/docs/supported-timezone-ids) for available timezones - Default: `America/New_York`.
     */
    description?: string;
    /**
     * Enable/disable state of schedule
     */
    enabled?: boolean;
    /**
     * Name of the schedule.
     */
    name: string;
    /**
     * Owner team id of the schedule.
     */
    ownerTeamId?: string;
    /**
     * The description of schedule.
     */
    timezone?: string;
}

/**
 * A collection of values returned by getSchedule.
 */
export interface GetScheduleResult {
    /**
     * Timezone of schedule. Please look at [Supported Timezone Ids](https://docs.opsgenie.com/docs/supported-timezone-ids) for available timezones - Default: `America/New_York`.
     */
    readonly description?: string;
    /**
     * Enable/disable state of schedule
     */
    readonly enabled?: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    /**
     * Owner team id of the schedule.
     */
    readonly ownerTeamId?: string;
    /**
     * The description of schedule.
     */
    readonly timezone?: string;
}
/**
 * Manages a Schedule within Opsgenie.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as opsgenie from "@pulumi/opsgenie";
 *
 * const test = opsgenie.getSchedule({
 *     name: "sre-team schedule",
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getScheduleOutput(args: GetScheduleOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetScheduleResult> {
    return pulumi.output(args).apply((a: any) => getSchedule(a, opts))
}

/**
 * A collection of arguments for invoking getSchedule.
 */
export interface GetScheduleOutputArgs {
    /**
     * Timezone of schedule. Please look at [Supported Timezone Ids](https://docs.opsgenie.com/docs/supported-timezone-ids) for available timezones - Default: `America/New_York`.
     */
    description?: pulumi.Input<string>;
    /**
     * Enable/disable state of schedule
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Name of the schedule.
     */
    name: pulumi.Input<string>;
    /**
     * Owner team id of the schedule.
     */
    ownerTeamId?: pulumi.Input<string>;
    /**
     * The description of schedule.
     */
    timezone?: pulumi.Input<string>;
}
